### ISSUE TITLE
setting columns to MultiIndex is broken in newer pandas versions

### ISSUE THREAD

**Issue by Swarchal** [Swarchal/meld#1]
`colfuncs.inflate_cols()` doesn't work anymore because MultiIndex class has changed, resulting in a length mis-match error.

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/softhpc/anaconda/CentOS7/forPython3/5.0.1/lib/python3.6/site-packages/pandas/core/generic.py", line 3094, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/src/properties.pyx", line 65, in pandas._libs.lib.AxisProperty.__set__
  File "/softhpc/anaconda/CentOS7/forPython3/5.0.1/lib/python3.6/site-packages/pandas/core/generic.py", line 473, in _set_axis
    self._data.set_axis(axis, labels)
  File "/softhpc/anaconda/CentOS7/forPython3/5.0.1/lib/python3.6/site-packages/pandas/core/internals.py", line 2836, in set_axis
    (old_len, new_len))
ValueError: Length mismatch: Expected axis has 3 elements, new values have 2 elements
```

**Comment by Swarchal** [comment]
Not actually using `colfuncs.inflate_cols()` in the ingestion workflow.
